### Looping backwards

In [1]:
colors=['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")

purple yellow green red 

In [2]:
for color in reversed(colors):
    print(color,end=" ")

purple yellow green red 

### Looping in sorted List

In [3]:
colors=['red','green','yellow','purple']
for color in sorted(colors,reverse=True):
    print(color,end=" ")

yellow red purple green 

In [4]:
colors=['red','green','yellow','purple']
for color in sorted(colors,reverse=True):
    print(color,end=" ")

yellow red purple green 

###
- if x<=y and y<=z:
- if x<=y<=z:
- if x==True
- if x:

### Pandas

In [1]:
import pandas as pd

In [4]:
dt = {'Id':[11,12,13,14,15],
     'first_name':['A','B','C','D','E'],
     'company':['aa','bb','cc','dd','ee'],
     'address':['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt=pd.DataFrame(dt)

In [5]:
print (mydt)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [6]:
import os

In [7]:
os.chdir("pathfile")#saves the current location

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'pathfile'

In [9]:
mydt.to_csv('working file.csv',index=False)

### Reading the data from CSV file

In [15]:
mydata=pd.read_csv('working file.csv')

In [16]:
print(mydata)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [17]:
mydata1=pd.read_csv('working file.csv',skiprows=1,names=["CustId","Name","Company","Address"])

In [18]:
print(mydata)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [23]:
mydata1=pd.read_csv('working file.csv',skiprows=[1,2,3],names=["CustId","Name","Company","Address"])

In [24]:
print(mydata1)

  CustId        Name  Company  Address
0     Id  first_name  company  address
1     14           D       dd      Hyd
2     15           E       ee      Hyd


In [25]:
pwd

'C:\\Users\\brigh\\python'

### Print Only Two Columns
### Print the large value from custID column -- max
### Print the least value from custID column -- min
### Average f custID coloumn--sum(li)/len(li)

In [31]:
mydata1.dropna(inplace=True)
large5=mydata1.nlargest(2,"CustId")
large5

TypeError: Column 'CustId' has dtype object, cannot use method 'nlargest' with this dtype

In [32]:
mydata1.min()

CustId          14
Name             D
Company    company
Address        Hyd
dtype: object

In [34]:
mydata1=pd.read_csv('working file.csv',skiprows=1,
                    names=["CustId","Name","company","Adress"])
df = pd.DataFrame(mydata1)
df[df.columns[1:3]] 


Name company
0    A      aa
1    B      bb
2    C      cc
3    D      dd
4    E      ee

In [36]:
print(mydata1['CustId'].mean())

13.0


### Numpy - Working with Multi Dimensional array
- Numpy array is a bit like python list
- Numpy array is data structure of Numpy Lib
- it's short name for Numeric Python or Numerical Python

In [37]:
import numpy as np

In [38]:
li={1,2,3,4,5}
print(li,end=" ")

{1, 2, 3, 4, 5} 

In [39]:
array=np.array(li)
print(array)

{1, 2, 3, 4, 5}


In [41]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(2,3),(3,4)])
print(a2.shape)

(2, 3)
(3, 2)


In [43]:
a1=np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [ ]:
### 5 Questions
### 2 uestions Turtle Graphics -- 1 mandatory
### 3 Questions Python Programming -- 2 mandatory
### Last time for submission : 3:00pm

In [50]:
import turtle
t = turtle.Turtle()
t.fillcolor('red')
t.begin_fill()
t.circle(100)
t.end_fill()

Terminator: 